esphome:
  name: uap1-hcp
  friendly_name: uap1_hcp
  includes:
  - hoermann.h
  libraries:
  - Arduino
  - Stream
  - ModbusRTU=https://github.com/emelianov/modbus-esp8266
  - bblanchon/ArduinoJson
  on_boot:
    priority: 600
    then:
      lambda: !lambda |-
        hoermannEngine->setup();

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret fallback_ssid
    password: !secret fallback_password

captive_portal:

cover:
- platform: template
  name: "Garage Door"
  id: garage_door
  device_class: garage
  lambda: !lambda |-
    if (hoermannEngine->state->coverState == "open") {
      return COVER_OPEN;
    } else {
      return COVER_CLOSED;
    }
  open_action: 
    - lambda: !lambda |-
      hoermannEngine->openDoor();
  close_action:
    - lambda: !lambda |-
      hoermannEngine->closeDoor(); 
  stop_action:
    - lambda: !lambda |-
      hoermannEngine->stopDoor();